//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tauseefolx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionItem
    {
        public int AuctionItemid { get; set; }
        public Nullable<int> SellItemid { get; set; }
        public Nullable<int> Buyerid { get; set; }
        public string Auctionprice { get; set; }
        public string SoldStatus { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
