//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tauseefolx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biddingtype
    {
        public int Biddingtypeid { get; set; }
        public string Biddingtype1 { get; set; }
    }
}
