//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tauseefolx.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class olxappEntities : DbContext
    {
        public olxappEntities()
            : base("name=olxappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuctionItem> AuctionItems { get; set; }
        public virtual DbSet<Biddingtype> Biddingtypes { get; set; }
        public virtual DbSet<BuyItem> BuyItems { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Usertable> Usertables { get; set; }
        public virtual DbSet<SellItem> SellItems { get; set; }
    }
}
