//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tauseefolx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellItem
    {
        public int SellItemid { get; set; }
        public Nullable<int> Usertableid { get; set; }
        public string Productname { get; set; }
        public string Productdescription { get; set; }
        public string Productimageone { get; set; }
        public string Productimagetwo { get; set; }
        public string Productimagethree { get; set; }
        public string Productimagefour { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Sold { get; set; }
        public string LowestBiddingPrice { get; set; }
        public Nullable<System.DateTime> Auctiondate { get; set; }
        public string AuctionPlace { get; set; }
        public string AuctionZipcode { get; set; }
        public string Auctionaddress { get; set; }
        public string Category { get; set; }
    }
}
